// ESLint flat config (CI runs `npm run lint`).
import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'dev-dist',
      'coverage',
      // Generated by `supabase gen types`; never hand-edited.
      'src/types/database.ts',
      // Deno runtime with its own tooling (`deno lint`).
      'supabase/functions',
    ],
  },
  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      // Classic hook rules. The React Compiler rules in the plugin's
      // `recommended` preset are not used: this app does not run the compiler.
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      // Route components are default-exported for React.lazy.
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
  {
    // Route table, shadcn primitives (export their variants) and the auth
    // provider (exports its hook) intentionally mix component/non-component exports.
    files: ['src/app/router.tsx', 'src/components/ui/**', 'src/features/auth/AuthProvider.tsx'],
    rules: { 'react-refresh/only-export-components': 'off' },
  },
  {
    files: ['tests/**/*.{ts,tsx}', '*.config.ts', 'scripts/**/*.ts'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
);
