/**
 * Supabase-generated database types.
 *
 * In the real project this file is generated by:
 *   supabase gen types typescript --project-id <id> > src/types/database.ts
 * It is NEVER hand-edited.
 *
 * Until the first migration (0001_init.sql) is applied and types are
 * generated, this placeholder provides the minimal shape the data layer
 * needs so the offline-first code can compile. snake_case is preserved
 * end to end (no camelCase mapping).
 */

/** Rows synced to IndexedDB for offline-first barangay staff screens. */
export interface households_row {
  id: string;
  barangay_id: string;
  purok_id: string | null;
  name: string | null;
  updated_at: string;
}

export interface patients_row {
  id: string;
  household_id: string | null;
  /** Server-assigned. Null for offline-created patients ("code pending"). */
  patient_code: string | null;
  surname: string | null;
  first_name: string | null;
  sex: string | null;
  birthdate: string | null;
  verification_status: string | null;
  updated_at: string;
}

export interface checkups_row {
  id: string;
  patient_id: string;
  checkup_date: string;
  updated_at: string;
}

export interface referrals_row {
  id: string;
  patient_id: string;
  status: string;
  updated_at: string;
}

export interface risk_rules_row {
  version: number;
  updated_at: string;
}

/**
 * Minimal Database type matching the shape `@supabase/supabase-js` expects.
 * Replaced wholesale by the generated file once migrations exist.
 */
export interface Database {
  public: {
    Tables: {
      households: {
        Row: households_row;
        Insert: households_row;
        Update: Partial<households_row>;
        Relationships: [];
      };
      patients: {
        Row: patients_row;
        Insert: patients_row;
        Update: Partial<patients_row>;
        Relationships: [];
      };
      checkups: {
        Row: checkups_row;
        Insert: checkups_row;
        Update: Partial<checkups_row>;
        Relationships: [];
      };
      referrals: {
        Row: referrals_row;
        Insert: referrals_row;
        Update: Partial<referrals_row>;
        Relationships: [];
      };
      risk_rules: {
        Row: risk_rules_row;
        Insert: risk_rules_row;
        Update: Partial<risk_rules_row>;
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
